version: "3"
services:
  # Setup shard for Europe region
  db-eu-region:
    container_name: db-eu-region
    image: mongo:3.6.15
    command: mongod --shardsvr --replSet eurs --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - 27017
    volumes:
      - ./cluster/db-eu:/data/db

  # Setup shard for United States region
  db-us-region:
    container_name: db-us-region
    image: mongo:3.6.15
    command: mongod --shardsvr --replSet usrs --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - 27017
    volumes:
      - ./cluster/db-us:/data/db

  # Setup configuration server to store metadata
  db-cfg:
    container_name: db-cfg
    image: mongo:3.6.15
    command: mongod --configsvr --replSet cfgrs1 --dbpath /data/db --port 27017
    expose:
      - 27017
    volumes:
      - ./cluster/db-cfg:/data/db

  # Setup router
  db-router:
    container_name: db-router
    image: mongo:3.6.15
    depends_on:
      - db-cfg
      - db-eu-region
      - db-us-region
    command: mongos --configdb cfgrs1/db-cfg:27017 --port 27017 --bind_ip_all
    ports:
      - 27019:27017
    expose:
      - 27017
